### ISSUE TITLE
pronto run throws an exception

### ISSUE THREAD

**Issue by proapi** [mmozuras/pronto-rails_best_practices#5]
I've installed the `pronto-rails_bes_practices` and running `pronto run` throws an exception like this:

```
/Users/pawelski/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/specification.rb:2158:in `method_missing': undefined method `this' for #<Gem::Specification:0x3ff37f86eb08 pronto-0.7.1> (NoMethodError)
        from /Users/pawelski/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/specification.rb:1057:in `find_active_stub_by_path'
        from /Users/pawelski/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:64:in `require'
        from /Users/pawelski/.rvm/gems/ruby-2.3.1/gems/pronto-rails_best_practices-0.7.0/lib/pronto/rails_best_practices.rb:1:in `<top (required)>'
        from /Users/pawelski/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `require'
        from /Users/pawelski/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `rescue in require'
        from /Users/pawelski/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:40:in `require'
        from /Users/pawelski/.rvm/gems/ruby-2.3.1/gems/pronto-0.7.1/lib/pronto/cli.rb:47:in `block in run'
        from /Users/pawelski/.rvm/gems/ruby-2.3.1/gems/pronto-0.7.1/lib/pronto/cli.rb:46:in `each'
        from /Users/pawelski/.rvm/gems/ruby-2.3.1/gems/pronto-0.7.1/lib/pronto/cli.rb:46:in `run'
        from /Users/pawelski/.rvm/gems/ruby-2.3.1/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
        from /Users/pawelski/.rvm/gems/ruby-2.3.1/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
        from /Users/pawelski/.rvm/gems/ruby-2.3.1/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
        from /Users/pawelski/.rvm/gems/ruby-2.3.1/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
        from /Users/pawelski/.rvm/gems/ruby-2.3.1/gems/pronto-0.7.1/bin/pronto:6:in `<top (required)>'
        from /Users/pawelski/.rvm/gems/ruby-2.3.1/bin/pronto:23:in `load'
        from /Users/pawelski/.rvm/gems/ruby-2.3.1/bin/pronto:23:in `<main>'
        from /Users/pawelski/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `eval'
        from /Users/pawelski/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `<main>'
```

This only happens on `ruby-2.3.1` I've the same setup on `ruby-2.2.1` and there it works fine.
I'm on macOS Sierra installed ruby via rvm.

If more informations needed I'll try to supply.

**Comment by mmozuras** [comment]
@proapi seems like [this issue](https://github.com/rubygems/rubygems/issues/1420).

What's the output for `gem -v`? Try running `gem update --system` and see if the issue still persists.

**Comment by Fabs** [comment]
Have the same issue. If I put the pronto gems into my Gemfile and run through bundle it is fine, but if I run it from the same gemset, that has rails and rails_best_practices gems, it explodes.

**Comment by mmozuras** [comment]
@proapi @Fabs have you tried running `gem -v` (output?) & `gem update --system`?

Any update on this issue. Does it still happen for you?

**Comment by proapi** [comment]
@mmozuras after upgrading rubygems on that version of ruby this error is no longer there! So we can close this issue.

**Comment by mmozuras** [comment]
@proapi cool, thanks! 🙇

**Comment by Fabs** [comment]
Same case here, updating the system worked. I had 2.5.1. Now I have 2.6.8.
